-- 009_calendar_events.sql
-- Stores calendar-only events that do not belong to a course.

CREATE TABLE IF NOT EXISTS calendar_events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL
        REFERENCES users(user_id)
        ON DELETE CASCADE,

    title VARCHAR(200) NOT NULL,

    -- Calendar-only events can be all-day events.
    event_date DATE NOT NULL,

    -- NULL means all-day / no specific time.
    event_time TIME,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX IF NOT EXISTS idx_calendar_events_user
    ON calendar_events(user_id);


CREATE INDEX IF NOT EXISTS idx_calendar_events_user_date
    ON calendar_events(user_id, event_date);


CREATE TRIGGER trg_calendar_events_updated_at
BEFORE UPDATE ON calendar_events
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();